selenium-hub:
  restart: always
  image: selenium/hub:latest
  ports:
    - "4444:4444"
  environment:
     GRID_MAX_SESSION: 10
#selenium-chrome
selenium-chrome:
  restart: always
  image: selenium/node-chrome-debug
  environment:
    NODE_MAX_INSTANCES: 4
  stdin_open: true
  links:
    - selenium-hub:hub
#selenium-firefox
selenium-firefox:
  restart: always
  image: selenium/node-firefox-debug
  environment:
    NODE_MAX_INSTANCES: 4
  links:
    - selenium-hub:hub
